=== KenEucker/moltensteelman-website/content/project/project.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "page-heading": {
      "type": "string",
      "id": "page-heading"
    },
    "description-title": {
      "type": "string",
      "id": "description-title"
    },
    "description": {
      "type": "string",
      "id": "description"
    },
    "main-video": {
      "type": "string",
      "id": "main-video"
    },
    "callout-title": {
      "type": "string",
      "id": "callout-title"
    },
    "callout-description": {
      "type": "string",
      "id": "callout-description"
    },
    "callout-button1": {
      "type": "string",
      "id": "callout-button1"
    },
    "callout-button2": {
      "type": "string",
      "id": "callout-button2"
    },
    "bullets": {
      "type": "array",
      "uniqueItems": false,
      "items": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "id": "amount"
          },
          "name": {
            "type": "string",
            "id": "name"
          }
        },
        "id": "4",
        "required": [
          "amount",
          "name"
        ]
      },
      "id": "bullets"
    },
    "images-heading": {
      "type": "string",
      "id": "images-heading"
    },
    "images": {
      "type": "array",
      "uniqueItems": false,
      "items": {
        "type": "object",
        "properties": {
          "image": {
            "type": "string",
            "id": "image"
          },
          "alt": {
            "type": "string",
            "id": "alt"
          }
        },
        "id": "38",
        "required": [
          "image",
          "alt"
        ]
      },
      "id": "images"
    },
    "links": {
      "type": "array",
      "uniqueItems": false,
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "id": "text"
          },
          "link": {
            "type": "string",
            "id": "link"
          }
        },
        "id": "2",
        "required": [
          "text",
          "link"
        ]
      },
      "id": "links"
    },
    "points": {
      "type": "array",
      "uniqueItems": false,
      "items": {
        "type": "object",
        "properties": {
          "heading": {
            "type": "string",
            "id": "heading"
          },
          "description": {
            "type": "string",
            "id": "description"
          }
        },
        "id": "2",
        "required": [
          "heading",
          "description"
        ]
      },
      "id": "points"
    },
    "navigation-links": {
      "type": "array",
      "uniqueItems": false,
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "id": "text"
          },
          "link": {
            "type": "string",
            "id": "link"
          }
        },
        "id": "1",
        "required": [
          "text",
          "link"
        ]
      },
      "id": "navigation-links"
    }
  },
  "id": "/",
  "required": [
    "page-heading",
    "description-title",
    "description",
    "main-video",
    "callout-title",
    "callout-description",
    "callout-button1",
    "callout-button2",
    "bullets",
    "images-heading",
    "images",
    "links",
    "points",
    "navigation-links"
  ]
}

=== KenEucker/moltensteelman-website/content/project/flamboni.json
{
  "page-heading": "The Flamboni",
  "description-title": "The Flamboni",
  "description": "The Flamboni carries our most powerful flame cannon and serves as our project support vehicle. Shoots flame plumes and rolling fireballs 30 feet in the air!  We stretched a golf cart frame to create the right proportion for this small-scale replica ice resurfacing machine and we custom fabbed the vintage bomber shark themed body.  ",
  "main-video": "https://www.youtube.com/embed/KqgbLZrsQVw",
  "callout-title": "\"A flame for everyone\"",
  "callout-description": "That it is",
  "callout-button1": "",
  "callout-button2": "",
  "bullets": [
    {
      "amount": 100,
      "name": "lbs of propane"
    }
  ],
  "images-heading": "Photos",
  "images": [
    {
      "image": "../../assets/img/2010FlamSOAK2.jpg",
      "alt": "Pair of pyrosaurus'"
    },
    {
      "image": "../../assets/img/2010FlamboniSOAK1.jpg",
      "alt": "Pair of pyrosaurus'"
    },
    {
      "image": "../../assets/img/ACME-2013.jpg",
      "alt": "Pair of pyrosaurus'"
    },
    {
      "image": "../../assets/img/Amish-2015.jpg",
      "alt": "Pair of pyrosaurus'"
    },
    {
      "image": "../../assets/img/BurnOut2010.jpg",
      "alt": "Pair of pyrosaurus'"
    },
    {
      "image": "../../assets/img/Flamboni-ACME-2013.jpg",
      "alt": "Pair of pyrosaurus'"
    },
    {
      "image": "../../assets/img/Flamboni-SCI-13.jpg",
      "alt": "Pair of pyrosaurus'"
    },
    {
      "image": "../../assets/img/Flamboni2013.jpg",
      "alt": "Pair of pyrosaurus'"
    }
  ],
  "links": [
    {
      "text": "Facebook",
      "link": "http://facebook.com"
    }
  ],
  "points": [
    {
      "heading": "Specifications",
      "description": "7 tons (14,250 lbs) or about the weight of 4 cars<br>The Walking Beast weighs more than most monster trucks!<br>Height 11 feet<br>Width 8 feet 4 inches<br>Length 24 feet<br>Ground Pressure 20.8 psi when standing on four legs<br>(as compared to 30 psi for a standard passenger car)"
    },
    {
      "heading": "Powered By",
      "description": "454 cu. in. Big block Chevy V-8 <br>TH400 transmission modified with 475 straight cut gears <br>Two Klune-V extreme under drive Goliath planetary gear reduction boxes <br>Rockwell 2 1/2 ton military differential modified with custom 5 ton parts <br>Final Drive Ratio is 125:1 <br>Fuel Consumption is 2 gallons gasoline per mile (GPM) <br>"
    },
    {
      "heading": "Construction",
      "description": "Linkage - 6-bar linkage system designed and patented by Joe Klann for walking machines.<br>The Walking Beast  linkage has 56 pivot points and uses 114 bearings.<br>Metals Used - Steel, aluminum, 1040, 4130, 4140, 4340, and 8620 chromium and molybdenum alloy<br>Method - Frame, legs and linkage are tubing cut, notched and welded, or CNC plasma cut, and then formed on a press brake and welded together to form box or angle structures. All pivot points and pins are CNC machined."
    }
  ],
  "navigation-links": [
    {
      "text": "Pyrosaurus",
      "link": "/pyrosaurus"
    },
    {
      "text": "The Mini Walking Beast",
      "link": "/theminiwalkingbeast"
    },
    {
      "text": "Cherry",
      "link": "/cherry"
    }
  ]
}

=== KenEucker/moltensteelman-website/content/project/sarp10.json
{
    "page-heading": "The SARP10",
    "description-title": "The SARP10",
    "description": "It's a spaceship!",
    "main-video": "https://www.youtube.com/embed/KqgbLZrsQVw",
    "callout-title": "\"A masterful feat of engineering\"",
    "callout-description": "That it is",
    "callout-button1": "",
    "callout-button2": "",
    "bullets": [
        {
            "amount": 2,
            "name": "legs"
        }
    ],
    "images-heading": "Photos",
    "images": [
        {
            "image":"../../assets/img/2010moopieSARP10.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-01.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-02.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-03.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-05.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-06.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-07.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-08.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-09.jpg",
            "alt":"Pair of pyrosaurus'"
        },
        {
            "image":"../../assets/img/OP-10.jpg",
            "alt":"Pair of pyrosaurus'"
        }
        ],
    "links": [
        {
            "text": "Facebook",
            "link": "http://facebook.com"
        }
    ],
    "points": [
        {
            "heading": "Specifications",
            "description": "7 tons (14,250 lbs) or about the weight of 4 cars<br>The Walking Beast weighs more than most monster trucks!<br>Height 11 feet<br>Width 8 feet 4 inches<br>Length 24 feet<br>Ground Pressure 20.8 psi when standing on four legs<br>(as compared to 30 psi for a standard passenger car)"
        },
        {
            "heading": "Powered By",
            "description": "454 cu. in. Big block Chevy V-8 <br>TH400 transmission modified with 475 straight cut gears <br>Two Klune-V extreme under drive Goliath planetary gear reduction boxes <br>Rockwell 2 1/2 ton military differential modified with custom 5 ton parts <br>Final Drive Ratio is 125:1 <br>Fuel Consumption is 2 gallons gasoline per mile (GPM) <br>"
        },
        {
            "heading": "Construction",
            "description": "Linkage - 6-bar linkage system designed and patented by Joe Klann for walking machines.<br>The Walking Beast  linkage has 56 pivot points and uses 114 bearings.<br>Metals Used - Steel, aluminum, 1040, 4130, 4140, 4340, and 8620 chromium and molybdenum alloy<br>Method - Frame, legs and linkage are tubing cut, notched and welded, or CNC plasma cut, and then formed on a press brake and welded together to form box or angle structures. All pivot points and pins are CNC machined."
        }
    ],
    "navigation-links": [
        {
            "text": "Pyrosaurus",
            "link": "/pyrosaurus"
        },
        {
            "text": "The Mini Walking Beast",
            "link": "/theminiwalkingbeast"
        },
        {
            "text": "Cherry",
            "link": "/cherry"
        }
    ]
}
