=== KenEucker/moltensteelman-website/content/content-page/content-page.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "colors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "text-field-text": {
      "type": "string"
    },
    "buy-button-text": {
      "type": "string"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "link": {
            "type": "string"
          }
        }
      }
    },
    "navigation-links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "link": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== KenEucker/moltensteelman-website/content/product/pyrosaurus.json
{
    "title": "Pyrosaurus",
    "description": "Fire breathing mini saurus on a globe that ignites the magician in you.",
    "colors": ["blue","red","green"],
    "text-field-text": "Inscription",
    "buy-button-text": "Place Order",
    "links": [
        {
            "text": "Facebook",
            "link": "http://facebook.com"
        },
        {
            "text": "Etsy",
            "link": "http://etsy.com"
        },
        {
            "text": "GoFundMe",
            "link": "http://gofundme.com"
        }
    ],
    "navigation-links": [
        {
            "text": "Home",
            "link": "/"
        },
        {
            "text": "The Mini Beast",
            "link": "/minibeast"
        }
    ]
}
